[package]
name = "bindings"
version = "0.1.0"
edition = "2018"

[dependencies]
winrt = "0.7.0"

[build-dependencies]
winrt = "0.7.0"

[package.metadata.winrt.dependencies]
"Microsoft.Windows.SDK.Contracts" = "10.0.19041.1"
